### ISSUE TITLE
ACF ?

### ISSUE THREAD

**Issue by glados1337** [Sceko/bbFlarum#1]
Hey,

Link on ACF plugin please.. i dont know you using i stuck at that, thx

**Comment by glados1337** [comment]
On my theme this plugin didnt work, ye i try remove wp footer from bbpress.php and nothing changed like this.

http://souls.funsite.cz/forums/

**Comment by Sceko** [comment]
Install https://wordpress.org/plugins/advanced-custom-fields/
And add forum group like this http://i.pics.rs/VJXsO

**Comment by glados1337** [comment]
Wow it's interesting how one plugin can make a huge change final two things to fix (i hope).

1) Page look like ok when im not loggen, when i log:   https://ctrlv.cz/juMK        need a padding from top, container code didnt work via child theme css.

2) Imortant thing: I cant creat a new topic, on left i have categories + in dark souls 1 a forum "rady a tipy" and page still called 404 at Faviicon.

After this two, its will be complete i hope, looking nice ;)

**Comment by Sceko** [comment]
1. Disable Admib Bar in theme function add show_admin_bar(false);
2. Problem in your themes and wordpress registration not work on your site.

**Comment by glados1337** [comment]
I try disable few things and test it on older PHP, not all host have 7.0 like main, tommorow i give you report, thanks, gn.

**Comment by glados1337** [comment]
On two site, different still working :). Thanks for a respond.
