### ISSUE TITLE
Translation placefolder

### ISSUE THREAD

**Issue by glados1337** [Sceko/bbFlarum#2]
Hey again,

I translating via Loco Translate and cant translate placeholder like then: https://ctrlv.cz/shots/2016/12/08/Ko8C.png , Thank you ;)

Maybe isnt bad idea to make at the footer: Powered by bbPress, sceko theme.  
Old bbpress looks like 2003 and your theme is modern, why not write signature ;)

**Comment by Sceko** [comment]
I change today footer <?php printf(__( '%1$s is proudly powered by %2$s' ), get_bloginfo('name'), '<a href="http://www.github.com/Sceko/bbFlarum">bbPress</a>'); ?></a>

Sorry i forgot to change that, now is fixed update form-topic.php
